import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  documentationSidebar: [
    'index',
    {
      type: 'category',
      label: 'Getting started',
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: 'Account',
      items: [{type: 'autogenerated', dirName: 'account'}],
    },
    {
      type: 'category',
      label: 'Organizations',
      items: [{type: 'autogenerated', dirName: 'organizations'}],
    },
    {
      type: 'category',
      label: 'Repositories',
      items: [{type: 'autogenerated', dirName: 'repositories'}],
    },
    {
      type: 'category',
      label: 'Configure repositories',
      items: [{type: 'autogenerated', dirName: 'repositories-configure'}],
    },
    {
      type: 'category',
      label: 'Coverage reporter',
      items: [{type: 'autogenerated', dirName: 'coverage-reporter'}],
    },
    {
      type: 'category',
      label: 'Codacy API',
      items: [{type: 'autogenerated', dirName: 'codacy-api'}],
    },
    {
      type: 'category',
      label: 'Codacy AI',
      items: [{type: 'autogenerated', dirName: 'codacy-ai'}],
    },
    {
      type: 'category',
      label: 'Codacy Guardrails',
      items: [{type: 'autogenerated', dirName: 'codacy-guardrails'}],
    },
    {
      type: 'category',
      label: 'Enterprise cloud',
      items: [{type: 'autogenerated', dirName: 'enterprise-cloud'}],
    },
    {
      type: 'category',
      label: 'FAQ',
      items: [{type: 'autogenerated', dirName: 'faq'}],
    },
    'special-thanks',
  ],
  releaseNotesSidebar: [{type: 'autogenerated', dirName: 'release-notes'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
