import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

import {gettingStartedOrder} from './docs/getting-started/_order';
import {accountOrder} from './docs/account/_order';
import {codacyApiOrder} from './docs/codacy-api/_order';
import {codacyGuardrailsOrder} from './docs/codacy-guardrails/_order';
import {coverageReporterOrder} from './docs/coverage-reporter/_order';
import {faqOrder} from './docs/faq/_order';
import {organizationsOrder} from './docs/organizations/_order';
import {repositoriesOrder} from './docs/repositories/_order';
import {repositoriesConfigureOrder} from './docs/repositories-configure/_order';
import {releaseNotesSidebarOrder} from './docs/release-notes/_order';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  documentationSidebar: [
    {
      type: 'category',
      label: 'Getting started',
      items: gettingStartedOrder,
    },
    {
      type: 'category',
      label: 'Codacy Guardrails (IDE Extension)',
      items: codacyGuardrailsOrder,
    },
    {
      type: 'category',
      label: 'Codacy AI',
      items: [{type: 'autogenerated', dirName: 'codacy-ai'}],
    },
    {
      type: 'category',
      label: 'Repositories on Codacy',
      items: repositoriesOrder,
    },
    {
      type: 'category',
      label: 'Configuring your repositories',
      items: repositoriesConfigureOrder,
    },
    {
      type: 'category',
      label: 'Organizations',
      items: organizationsOrder,
    },
    {
      type: 'category',
      label: 'Enterprise cloud',
      items: [{type: 'autogenerated', dirName: 'enterprise-cloud'}],
    },
    {
      type: 'category',
      label: 'Your account',
      items: accountOrder,
    },
    {
      type: 'category',
      label: 'Codacy API',
      items: codacyApiOrder,
    },
    {
      type: 'category',
      label: 'Coverage reporter',
      items: coverageReporterOrder,
    },
    {
      type: 'category',
      label: 'FAQ',
      items: faqOrder,
    },
    'special-thanks',
  ],
  releaseNotesSidebar: releaseNotesSidebarOrder,
};

export default sidebars;
