name: Alex Recommends

on: pull_request

jobs:
  alex:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master' && !startsWith(github.ref, 'refs/heads/release/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCOUNT_TOKEN }}
          submodules: true
          fetch-depth: 0

      - name: Comment on pull request
        uses: brown-ccv/alex-recommends@v1.1.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message_id: 'alex'
          glob_pattern: "**/*.md"
