name: Enforce labels

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]

jobs:
  enforce-label:
    runs-on: ubuntu-latest
    steps:
    - uses: yogevbd/enforce-label-action@2.2.2
      with:
        BANNED_LABELS: "don't merge"
