name: markdown-link-check

on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        folder-path: 'docs'
        file-path: './README.md, ./CONTRIBUTING.md'